import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./ui/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        themeGreyColor: "var(--themeGreyColor)",
        themeBlueColor: "var(--themeBlueColor)",
        themeSecondayBlue: "var(--themeSecondayBlue)",
        themeYellowColor: "var(--themeYellowColor)",
        themelightGreyColor: "var(--themelightGreyColor)",
        themeDarkGreyColor: "var(--themeDarkGreyColor)",
        themeSilverGreyColor: "var(--themeSilverGreyColor)",
        themeBorderGrey: "var(--themeBorderGrey)",
        themeErrorText: "var(--themeErrorText)",
        tableRoleGrey: "var(--tableRoleGrey)",
        borderLightBlue: "var(--borderLightBlue)",
        buttonBgWhiteBlue: "var(--buttonBgWhiteBlue)",
        themeDotGreenColor: "var(--themeDotGreenColor)",
        themeDotGreyColor: "var(--themeDotGreyColor)",
        themeDotRedColor: "var(--themeDotRedColor)",
        themeDotBlueColor: "var(--themeDotBlueColor)",
        themeStatsRedColor: "var(--themeStatsRedColor)",
        themeStatsBlueColor: "var(--themeStatsBlueColor)",
        themeStatsGreenColor: "var(--themeStatsGreenColor)",
        themeStatsYellowColor: "var(--themeStatsYellowColor)",
        themeHeadingBlue: "var(--themeHeadingBlue)",
        moduleCheckBoxBg: "var(--moduleCheckBoxBg)",
        assayBorder: "var(--assayBorder)",
        tabBoxShadow: "var(--tabBoxShadow)",
        tableBackground: "var(--tableBackground)",
        grayHover: "var(--grayHover)",
        grayMessage: "var(--grayMessage)",
        blueLightBg: "var(--blueLightBg)",
        messageDarkBlue: "var(--messageDarkBlue)",
        disabledTextButtonBlue: "var(--disabledTextButtonBlue)",
        disabledBlueButton: "var(--disabledBlueButton)",
        lightGreen: "var(--lightGreen)",
        lightMerun: "var(--lightMerun)",
        lightBlue: "var(--lightBlue)",
        lightGrey: "var(--lightGrey)",
        textLightRed: "var(--textLightRed)",
        textLightGreen: "var(--textLightGreen)",
        failedCategoryRed: "var(--failedCategoryRed)",
        infoCategoryYellow: "var(--infoCategoryYellow)",
        doneCategoryGreen: "var(--doneCategoryGreen)",
        themeLightBlueColor: "var(--themeLightBlueColor)"
      },
    },
  },
  plugins: [],
};
export default config;
